### ISSUE TITLE
Package for Nix / NixOS

### ISSUE THREAD

**Issue by pinage404** [Merrit/vscode-runner#16]
Hello,

Thanks for this project !

For your information, i have [packaged it](https://gitlab.com/pinage404/dotfiles/-/commit/dc474aa444c7bda0b8066eb432014c7d649bc748) for [Nix / NixOS](https://nixos.org/) for my personal use

I hope someone will reuse it to make it available to more people!

Feel free to close this issue

**Comment by Merrit** [comment]
Nice! I am glad you find it useful :blue_heart: 

I am not familiar with Nix; is there an easy install command for it, so instructions can be added to the README?

**Comment by pinage404** [comment]
Nix is not a familiar package manager

Nix is not really about executing commands to install things

Nix is designed to be declarative and highly reproducible with configuration files

It uses files to describe the desired configuration, and then we execute commands to apply that configuration

The easiest way to install it would be to add this to the configuration

```nix
{
   environment.systemPackages = [
      (builtins.getFlake "gitlab:pinage404/dotfiles/eeb5580e8a22ab7f61bc13a5149b1ef32ffd7ccd").packages.x86_64-linux.vscode-runner # add a package without overlay and without flake
   ];
}
```

I have tried to [document it here](https://gitlab.com/pinage404/dotfiles/-/blob/ab1017eececaa8b090240a0e4619c476edbba648/docs/packages.md#using-packages) with a more common (but also more verbose) installation method

**Comment by Merrit** [comment]
Cool! :)

Thanks for letting me know~ Hopefully this issue will be helpful for any other Nix users :blue_heart:
