### ISSUE TITLE
vscode-runner added to nixpkgs

### ISSUE THREAD

**Issue by pinage404** [Merrit/vscode-runner#17]
Hello,

For your information, [this project has been packaged to nixpkgs](https://github.com/NixOS/nixpkgs/pull/330659)
After making a package for myself https://github.com/Merrit/vscode-runner/issues/16 i have upsteamed it

It is now more easier for any [Nix](https://nixos.org/) user to use your package

```sh
nix-shell --packages vscode-runner
```

https://search.nixos.org/packages?channel=unstable&type=packages&query=vscode-runner

https://repology.org/project/vscode-runner/versions

Feel free to close this issue

**Comment by Merrit** [comment]
Nice! I documented this in the README with c2a9f3ed9d5f69e7c6455cbf9e5f27d2f44e892c.

Thanks for letting me know :tada: :grin:
