### ISSUE TITLE
[Enhancement] Handle Remote Workspace

### ISSUE THREAD

**Issue by chinggg** [Merrit/vscode-runner#3]
Thanks for making this krunner plugin!  Now it handles remote workspace as normal path to open instead of opening a remote SSH workspace.

It should be possible to open a remote workspace from cli https://stackoverflow.com/questions/60144074/how-to-open-a-remote-folder-from-command-line-in-vs-code

I guess some modification can be made here https://github.com/Merrit/vscode-runner/blob/main/bin/vscode_runner.dart#L135

**Comment by Merrit** [comment]
Judging by the answer in that Stackoverflow it does look possible - probably check the path that was received, something like if it starts with `ssh` then format it appropriately.

I haven't used KDE in some time, but I'd be happy to answer questions if you wanted to make a PR. :)

**Comment by Merrit** [comment]
Resolved with #4
