### ISSUE TITLE
Support Alternative VS Code Installations

### ISSUE THREAD

**Issue by hmnd** [Merrit/vscode-runner#5]
Would be awesome if this supported setting a custom VS Code config path + executable name, so that VS Code Insiders or VSCodium could be compatible.

**Comment by Merrit** [comment]
I agree, it would be nice to support those :)

**Comment by idimou** [comment]
If you have the time please take a look at supporting VS Code Insiders. We'd be grateful.

**Comment by Merrit** [comment]
I am in the process of adding support for Insiders, coming shortly :)
