### ISSUE TITLE
Remote projects

### ISSUE THREAD

**Issue by asd2003ru** [Merrit/vscode-runner#6]
Dont open remote projects from Project Manager. Only local.

**Comment by asd2003ru** [comment]
For open remote workspace or folder:
Example in project.json: vscode-remote://ssh-remote+hostname.com/home/asd/Projects/tgnotify/tgnotify.code-workspace
Execute: code --remote ssh-remote+hostname.com /home/asd/Projects/tgnotify/tgnotify.code-workspace

**Comment by Merrit** [comment]
> Dont open remote projects from Project Manager. Only local.

I'm not sure I understand.. are you saying it fails to open remote projects?
